### ISSUE TITLE
wish: option to customize filenames

### ISSUE THREAD

**Issue by jmlucjav** [mihaifm/bufstop#10]
when showing up list of open buffers, it is sometime very handy to exclude extensions so you can show up more files...

or, if you want to really get fancy, you could allow using help:filename-modifiers syntax to customize how files are shows, as bufferline does with bufferline_fname_mod option.

thanks for this great plugin!

**Comment by mihaifm** [comment]
Fixed: 75485107df54e5dc0172f7e91b7f8b52fbeeff67

To use it, implement g:BufstopFileFormatFunc in your vimrc:

    let g:BufstopFileFormatFunc = 'MyBufstopFileFormat'
    function! MyBufstopFileFormat(shortname)
      return fnamemodify(a:shortname, ':t:r')
    endfunc
