### ISSUE TITLE
After setting `g:BufstopSpeedKeys`, <leader>1 doesn't do anything

### ISSUE THREAD

**Issue by jamischarles** [mihaifm/bufstop#15]
Loving this plugin.

Here's something weird.

After setting `BufstopAutoSpeedToggle`, `<leader>1` doesn't seem to do anything. `<leader>2` does what I expect it to.

Is this intended behavior? For now, I'm fixing it by setting `g:BufstopSpeedKeys` to `let g:BufstopSpeedKeys = ["0", "1", "2", "3", "4", "5"]`

**Comment by mihaifm** [comment]
Yes..<leader>1 isn't supposed to do anything, since 1 reffers to the most recently used file (current file). <leader>3 for example is the 3rd recent file. I guess it's a matter of convention...

**Comment by jamischarles** [comment]
That's interesting. I can see how mapping it to the array indeces makes sense conceptually, but this renders `<leader>1` useless. I have a workaround though. Thx.
