### ISSUE TITLE
Enable devicons, add filetype "bufstop" to Bufstop window for users to be able to detect it and color it if they like

### ISSUE THREAD

**Issue by poetaman** [mihaifm/bufstop#20]
You will need two simple things:

1. Check if [vim-devicons](https://github.com/ryanoasis/vim-devicons)  plugin is loaded. If yes, then use the function `WebDevIconsGetFileTypeSymbol()` provided by it to get the file's icon (as discussed pointed [here](https://github.com/mhinz/vim-startify/blob/master/doc/startify.txt#L889-L895)) & prepend it to the file name column of Bufstop/BufstopPreview window.
2. Make sure to assign a unique filetype name like "bufstop" to your Bufstop window. This can be used by people who want to color the icons (you don't need to add any coloring code yourself). This is being discussed [here](https://github.com/ryanoasis/vim-devicons/issues/158).

The result will look something like this:

https://github.com/ryanoasis/vim-devicons#---1

**Comment by mihaifm** [comment]
Sounds cool, I'll investigate this when I have some time.

**Comment by mihaifm** [comment]
Took some time but it's done now :)

![image](https://github.com/mihaifm/bufstop/assets/981184/5fcbcc12-b416-4ea7-8a64-963e3dd00fa5)

To enable it, add this to your .vimrc after installing vim-devicons:

      let g:BufstopFileSymbolFunc = 'MyBufstopFileIcon'
      function MyBufstopFileIcon(path)
        return WebDevIconsGetFileTypeSymbol(a:path)
      endfunction
