### ISSUE TITLE
This is _the_ missing plugin

### ISSUE THREAD

**Issue by alextes** [mihaifm/bufstop#25]
Just came by to say I _love_ this plugin. imo, two or one key switching to the most recently used buffer is the logical endpoint for those who feel:
* jumplist can take n jumps to get back to the m most recently used file
* fuzzy finding files or buffers is too slow and doesn't muscle memory
* alternate file is useless if you need to go two or three files further back although I will admit that's 90% of my use
* something like harpoon is too much setup for you as your set of active files changes too quickly

So have some love ❤️ , this plugin is amazing, I think many would use it if only they knew about it.

Quick feature request, I think the Bufstop window is neat but kinda close to what a fuzzy finder can do. BufStopAutoSpeedToggle one key switching is great too but my F-keys are brightness, music, etc. besides they're far away. So I'm a big fan of `<leader>2` / `<leader>3`. However, BufStopSpeedToggle is not an option like BufStopAutoSpeedToggle. Would it make sense to add one?

**Comment by mihaifm** [comment]
Hey, thanks for the great feedback!

So BufStopSpeedToggle is the command and g:BufStopAutoSpeedToggle is the config option, they both do the same thing - enable the key mappings.

So if you want the `<leader>2 / <leader>3` mappings all you need is to add this in the .vimrc

     let g:BufstopAutoSpeedToggle = 1

No other settings required. Hope that helps, I also use it this way.

Cheers

**Comment by alextes** [comment]
Ah neat!
